name: CD-release

on:
  release:
    types:
      [published]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  publish:
    name: Publish Release to rudyx.org
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DAPP_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DAPP_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.DAPP_AWS_REGION }}
      SOURCE_DIR: 'tail-ui/build'
      PATHS: "/*"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Install dependencies"
        run: npm run ci-ui

      - name: "Clean the build"
        run: npm run build:clean

      - name: "Build the project"
        run: npm run build

      - name: Deploy to production
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DAPP_AWS_S3_PROD_BUCKET }}

      - name: Invalidate Production CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DAPP_PROD_DISTRIBUTION }}
