name: CI-kommiters
on:
  workflow_dispatch:
    inputs:
      SECRET_KEY:
        description: 'for decript the .env.enc file'
        required: true
        default: "mySecretPassword"
        type: string
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-env-kommiters:
    name: testing-environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Install the project"
        run: npm install

      - name: 'Create .env file in base .env.example'
        run: |
          touch .env
          echo 'SECRET="${{ github.event.inputs.SECRET_KEY }}"' >> .env

      - name: "Run the tests"
        run: npm test
